sudo: required

services:
  - docker

before_install:
  - docker pull mafiascum/forum-db:skeleton
  - docker run -d --name test_database -e MYSQL_ROOT_PASSWORD=password mafiascum/forum-db:skeleton
  - docker pull mafiascum/forum-tester:latest

script:
    - echo "TODO"

after_success:
  - test $TRAVIS_BRANCH = "develop" && test $TRAVIS_PULL_REQUEST = "false" && curl "http://$JENKINS_HOST/buildByToken/build?job=mafiascum-staging&token=$JENKINS_TOKEN"

  